# Generated by Django 5.0.1 on 2024-02-02 16:12

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('kpi', '0001_initial'), ('kpi', '0002_rename_s_active_department_is_active'), ('kpi', '0003_department_text_color'), ('kpi', '0004_department_back_color'), ('kpi', '0005_alter_department_text_color'), ('kpi', '0006_alter_department_text_color')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный статус')),
                ('text_color', models.CharField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#000000', max_length=7)),
                ('back_color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, unique=True, verbose_name='Наименование')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Процентная метрика')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPIPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный статус')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.category', verbose_name='Категория')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.department', verbose_name='Отдел')),
                ('entity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.entity', verbose_name='Производственный участок')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.kpi', verbose_name='KPI')),
            ],
        ),
        migrations.CreateModel(
            name='KPIValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_glidepath', models.BooleanField(default=False, verbose_name='Таргет')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2024', max_length=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Значение')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.kpiconfig', verbose_name='KPI')),
                ('kpi_phase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.kpiphase', verbose_name='Период')),
            ],
            options={
                'unique_together': {('year', 'is_glidepath', 'kpi_phase', 'kpi')},
            },
        ),
    ]
