# Generated by Django 5.0.1 on 2024-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_squashed_0006_alter_department_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
