# Generated by Django 5.0.1 on 2024-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='kpiphase',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
