# Generated by Django 5.0.1 on 2024-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_alter_department_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KPIValues',
            new_name='KPIValue',
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
